---
default:
  php_path: /path/to/php
  include_dir: runtasks
  is_logging: false
  is_stdout: true
  is_continue: true
  prefix_message: '[RunTasks_Runner::run]'

php_ini:
  memory_limit: '128M'
  time_limit: 30

groups:
  group1: []
